### ISSUE TITLE
请问face_area是如何确定的？

### ISSUE THREAD

**Issue by zzzyb009** [tonyiweb/face_merge_master#4]
你好~请问这个坐标是根据每个融合图来进行配置的吗？

![image](https://user-images.githubusercontent.com/22492671/60664813-68f96000-9e95-11e9-937e-38bfa78dde75.png)

具体的位置是这个对吗？

![image](https://user-images.githubusercontent.com/22492671/60665032-f5a41e00-9e95-11e9-920c-6082e6d8bedc.png)

**Comment by tonyiweb** [comment]
face_area是待融合图片人脸心形区域的大小和位置。

**Comment by zzzyb009** [comment]
> face_area是待融合图片人脸心形区域的大小和位置。

谢谢~了解了
